/**
 * Hằng số tên màn hình
 */
export const SCREENS = {
  // auth
  LOGIN: 'LOGIN',
  SIGN_UP: 'SIGN_UP',

  // myTabs
  HOME: 'HOME',
  CATEGORY: 'CATEGORY',
  CART: 'CART',
  NOTIFICATION: 'NOTIFICATION',
  ACCOUNT: 'ACCOUNT',

  // admin
  ADMIN_PANEL: 'ADMIN_PANEL',
  // category
  CATEGORY_CREATE: 'CATEGORY_CREATE',
  CATEGORY_EDIT: 'CATEGORY_EDIT',
  CATEGORY_LIST: 'CATEGORY_LIST',
  CATEGORY_SHOW: 'CATEGORY_SHOW',
  // product
  PRODUCT_CREATE: 'PRODUCT_CREATE',
  PRODUCT_EDIT: 'PRODUCT_EDIT',
  PRODUCT_LIST: 'PRODUCT_LIST',
  PRODUCT_SHOW: 'PRODUCT_SHOW',

  RATING_LIST: 'RATING_LIST',
  COMMENT_LIST: 'COMMENT_LIST',
  COMMENT_REPLY: 'COMMENT_REPLY',
  USER_LIST: 'USER_LIST',

  ORDER_EDIT: 'ORDER_EDIT',
  ORDER_LIST: 'ORDER_LIST',

  CHART: 'CHART',

  //
  PRODUCTS_BY_CATEGORY: 'PRODUCTS_BY_CATEGORY',
  USER_INFO: 'USER_INFO',
  ORDER_MANAGEMENT: 'ORDER_MANAGEMENT',
  USER_COMMENT: 'USER_COMMENT',
  USER_RATING: 'USER_RATING',
  PRODUCT_DETAIL: 'PRODUCT_DETAIL',
  SEARCH: 'SEARCH',
  CHANGE_LANGUAGE: 'CHANGE_LANGUAGE',
  MY_COMMENT_LIST: 'MY_COMMENT_LIST',
};
